name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew :commons-message:build -x test
    - name: Test with Gradle
      run: ./gradlew :commons-message:test
    - uses: actions/upload-artifact@v1
      env:
        SECRET_NAME_1: ${{ secrets.SECRET_NAME_1 }}
      if: failure()
      with:
        name: jacoco-test-report
        path: /home/runner/work/j-commons/j-commons/$SECRET_NAME_1/build/reports/tests/test
